create table if not exists public.clinic_expenses (
  id bigint generated by default as identity primary key,
  doctor_id uuid not null references auth.users(id) on delete cascade,
  clinic_id bigint not null references public.clinic_data(id) on delete cascade,
  amount numeric(12, 2) not null check (amount > 0),
  description text not null check (char_length(trim(description)) between 1 and 200),
  expense_date date not null default current_date,
  created_at timestamptz not null default now()
);

create index if not exists clinic_expenses_clinic_date_idx
  on public.clinic_expenses (clinic_id, expense_date);

alter table public.clinic_expenses enable row level security;

create policy "Doctors can manage their clinic expenses"
  on public.clinic_expenses
  for all
  to authenticated
  using (auth.uid() = doctor_id)
  with check (
    auth.uid() = doctor_id
    and exists (
      select 1 from public.clinic_data
      where clinic_data.id = clinic_id and clinic_data.doctor_id = auth.uid()
    )
  );
