create table if not exists public.support_reports (
  id bigint generated by default as identity primary key,
  doctor_id uuid not null references auth.users(id) on delete cascade,
  report_type text not null check (report_type in ('bug', 'suggestion', 'other')),
  message text not null check (char_length(trim(message)) between 1 and 1000),
  created_at timestamptz not null default now()
);

alter table public.support_reports enable row level security;

create policy "Doctors can submit their own reports"
  on public.support_reports
  for insert
  to authenticated
  with check (auth.uid() = doctor_id);

create policy "Doctors can read their own reports"
  on public.support_reports
  for select
  to authenticated
  using (auth.uid() = doctor_id);
