CREATE TABLE IF NOT EXISTS public.governorate (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz NOT NULL DEFAULT now(),
  name_ar text,
  name_en text
);

ALTER TABLE public.city ADD COLUMN IF NOT EXISTS governorate_id bigint REFERENCES public.governorate(id);
ALTER TABLE public.city ADD COLUMN IF NOT EXISTS parent_id bigint REFERENCES public.city(id);
ALTER TABLE public.city ADD COLUMN IF NOT EXISTS type text DEFAULT 'city';;
